blogs/urls.py
from django.urls import path
from blogs import views

app_name='blogs'

urlpatterns = [
    path ('', views.home_page),
    path ('post/<slug:slug>', views.PostDetailView.as_view(), name='post'),
    path ('featured/', views.FeaturedListView.as_view(), name='featured'),
    path ('Categorias/<slug:slug>', views.CategoryListView.as_view(), name='categoria'),
    path ('search/' , views.SearchResultsView.as_view() , name='search'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include ('django.contrib.auth.urls')),
    path ('', include ('blogs.urls')),
    path ('', include ('usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.views.generic import TemplateView

from usuarios import views


app_name = 'usuarios'

urlpatterns = [
    path('registration/', views.UserRegistration.as_view (), name='registration'),
    path('success/', TemplateView.as_view(template_name='usuarios/success_registration.html'), name='success')
]

blogs/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    overview = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    categories = models.ManyToManyField('Categorias')
    featured = models.BooleanField(default=False)
    pub_date =models.DateTimeField(default=timezone.now)


    def get_absolute_url(self):
        return reverse("blogs:post", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ["-date_created"]

    def __str__(self):
        return self.title

class Categorias(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
      
    class Meta:
        verbose_name_plural = "categorias"

    def get_absolute_url(self):
        return reverse("blogs:categorias", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

usuarios/models.py
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    
    def __str__(self):
        return f'{self.last_name},{self.first_name}'
    

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ("username", "email", "password1", "password2")

blogs/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.utils import timezone
from django.db.models import Q
from blogs.models import Post, Categorias



# Create your views here.
def home_page(request):
   posts= Post.objects.filter(
      pub_date__lte=timezone.now()
   )
   categorias= Categorias.objects.all()
   featured = Post.objects.filter(featured= True).filter(
      pub_date__lte=timezone.now()
   )[:3]
   

   context = {
      'posts':posts,
      'categorias':categorias,  
      'destacados': featured 
   }
   return render (request, 'blogs/home_page.html', context=context)

class PostDetailView(generic.DetailView):
   model = Post
   queryset = Post.objects.filter(featured= True).filter(
         pub_date__lte= timezone.now()
   )

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)   
      context['categorias'] = Categorias.objects.all()  
      return context
   
class FeaturedListView(generic.ListView):
   model = Post 
   template_name = 'blogs/results.html'


   def get_queryset(self):
      query = Post.objects.filter(featured= True).filter(
         pub_date__lte= timezone.now()
      )
      return query
   
   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)   
      context['categorias'] = Categorias.objects.all()  
      return context 

      
   
class CategoryListView(generic.ListView):
   model = Post 
   template_name = 'blogs/results.html'

   def get_queryset(self):
      query = self.request.path.replace('/categorias/', '')
      print(query)
      posts = Post.objects.filter(Categorias__slug=query).filter(
         pub_date__lte= timezone.now()
      )
      return posts
      
   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)   
      context['categorias'] = Categorias.objects.all()  
      return context
   

class SearchResultsView(generic.ListView):
   model = Post 
   template_name = 'blogs/results.html'

   def get_queryset(self):
      query = self.request.GET.get("search")
      posts = Post.objects.filter(
         Q (title__icontains=query) | Q(Categorias__title__icontains=query)
      ).filter(
         pub_date__lte= timezone.now()
      )
      return posts
      
   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)   
      context['categorias'] = Categorias.objects.all()  
      return context
   

usuarios/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import FormView

from usuarios.forms import RegisterForm

# Create your views here.

class UserRegistration(FormView):
    template_name= 'usuarios/registration.html'
    form_class = RegisterForm
    success_url=reverse_lazy('usuarios:success')

    def form_valid(self, form):
        form.save()
        return super(UserRegistration, self).form_valid(form)

blogs/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BlogDjango</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

{% include 'navbar.html' %}
{% block content %} {%endblock content %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

blogs/templates/blogs/featured.html
<div id="carouselIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        {% for f in featured %}
          <div class ="carousel-item {% if f == featured|first %}active{% endif %}">
              <div class ="px=5 p-md-5 mb-4 rounded text-bg-success bg-gradient" style="height: 300px">
                  <div class ="col-md-10 px-5 mx-5">
                      <h1 class ="display-4 fw-bold px-5">{{ f.title }}</h1>
                      <p class ="lead my-3 px-5">{{ f.overview }}</p>
                      <p class ="lead mb-0 px-5"><a href ="#" class="text-white fw-bold" >Continua leyendo...</a></p>
                  </div>
              </div>
          </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previamente</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Siguiente</span>
    </button>
</div>

blogs/templates/blogs/featured_list.html
{% extends 'base.html' %}

{% block content %} 
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
    
    <main class="container">
        
        <div class="row g-5">             
            <div class "col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border bottom">
                    Destacados
                </h3>
                {% for post in posts %}
                    <div class="card mb-3">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" class="card-img-top" alt="thumbnail">
                        {% endif %}
                        <div class ="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text">{{ post.overview }}</p>
                            <p class="card-text"><small class ="text-muted">Last update {{ post.pub_date.date }}</small></p>
                        </div>
                    </div>
                {% endfor %}

            </div>
            <div class=" md-4 ">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                        <h4 class="fst-italic"> ¿Quieres saber más? </h4>
                        <p class="mb-0"> Información adicional sobre lo que se encuentra en esta página. </p>
                    </div>
                    <div class="p-4">
                        <h4 class="fst-italic">¿Más cosas?</h4>
                    </div>
                </div>
            </div>
            
        </div>
{% endblock %}

blogs/templates/blogs/home_page.html
{% extends 'base.html' %}
 
{% block content %} 
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
    
    <main class="container">
        
        <div class="row g-5"> 
            
            <div class "col-md-12">
                {% include "blogs/featured.html" %}
            </div>
            
        </div>

        <div class="row g-5">             
            <div class "col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border bottom">
                    Artículos
                </h3>
                {% for post in posts %}
                    <article class = "blog-post">
                        <h2 class="blog-post-title mb-1">
                            {%comment %}<a href="{% url 'blogs:post' post.slug %}" style="text-decoration: none"
                                class="text-black">
                                {{post.title}}
                            </a>{% endcomment %}
                            <a href="{{post.get_absolute_url}}" style="text-decoration: none"
                                class="text-black">
                                {{post.title}}
                            </a>
                        </h2>
                        <p class="blog-post-meta">{{ post.pub_date.date}}, {{post.author}}</p>

                        <hr>
                        <p> {{post.overview}} </p>
                    </article>
                {% endfor %}

            </div>
            <div class=" md-4 ">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                        <h4 class="fst-italic"> ¿Quieres saber más? </h4>
                        <p class="mb-0"> Información adicional sobre lo que se encuentra en esta página. </p>
                    </div>
                    <div class="p-4">
                        <h4 class="fst-italic">¿Más cosas?</h4>
                    </div>
                </div>
            </div>
            
        </div>
    </main>    
</div>
{%endblock content %}

blogs/templates/blogs/post_detail.html
{% extends 'base.html' %}

{% block content %} 

<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
    
    <main class="container">
        
        <div class="row g-5"> 
          <div class "col-md-12">
            <div class"row">
                <div class="d-flex justify-content-between">
                    <h1>{{ post.title }}</h1>
                    <div class="align-self-end">Publicado: {{ post.pub_date.date }}</div>
                </div>
            </div>
            <hr class="d-none d-md-block my-2 mb-3 mt-2">

            <p>{{ post.content }}</p>
          
        </div>

    </main>
</div>

{%endblock content%}

blogs/templates/blogs/results.html
{% extends 'base.html' %}

{% block content %} 
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
    
    <main class="container">
        
        <div class="row g-5">             
            <div class "col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border bottom">
                    Destacados
                </h3>
                {% for post in posts %}
                    <div class="card mb-3">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" class="card-img-top" alt="thumbnail">
                        {% endif %}
                        <div class ="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text">{{ post.overview }}</p>
                            <p class="card-text"><small class ="text-muted">Last update {{ post.pub_date.date }}</small></p>
                        </div>
                    </div>
                {% endfor %}

            </div>
            <div class=" md-4 ">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                        <h4 class="fst-italic"> Encontrados </h4>
                        <p class="mb-0"> {{ posts | length }} </p>
                    </div>
                
                </div>
            </div>
            
        </div>
    </main>
</div>
{% endblock%}

blogs/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">BlogDjango</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogs:featured'%}">Destacados</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categorias
            </a>
            <ul class="dropdown-menu">
                {% for categoria in categorias %}
                    <li><a class="dropdown.item"
                            href="{% url 'blogs:categoria' categoria.slug %}" >{{ categoria.title }}</a></li>
                {% endfor %}
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search" action="{% url 'blogs:search'%}" method="get">  
          <input name= "search" class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Buscar</button>
        </form>
        {% if user.is_authenticated %}
          <a class="btn btn-outline-primary ms-2" href="{% url 'logout' %}" role="button">Sign Out</a>
        {% else %}
          <a class="btn btn-outline-primary ms-2" href="{% url 'login' %}" role="button">Sign In</a>
        {% endif %}
      </div>
    </div>
</nav>

usuarios/templates/usuarios/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
    
    <main class="container">
    
        <div class="row g-5"> 
            <div class "col-md-3"></div>

            <div class "col-md-6">   
        
                <div class ="w-100 m-auto text-center">
                    <form method="posts" class= "form-group">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-success">Register</button>
                    </form>
                </div>
            </div>

            <div class="col-md-3"></div>                            
        </div>

    </main>    
</div>
{% endblock %}

usuarios/templates/usuarios/success_registration.html
{% extends 'base.html' %}

{% block content %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
    
    <main class="container">
    
        <div class="row g-5"> 
            <div class "col-md-3"></div>

            <div class "col-md-6">   
        
                <div class ="w-100 m-auto text-center">

                   <h1>Registro exitoso</h1>
                   <a class="btn btn-outline-primary mb-5" href="{% url 'login' %}" role="button">Sign In</a>
                </div>
            </div>

            <div class="col-md-3"></div>                            
        </div>

    </main>    
</div>
{% endblock %}